#!/usr/bin/env python3
"""Build padded, native-scale Meridian prop runtime families and static catalog."""
from __future__ import annotations
import json
from pathlib import Path
from PIL import Image

ROOT=Path(__file__).resolve().parents[3]
PROJECT=ROOT/"custodian"
MANIFEST=PROJECT/"content/metadata/assets/meridian_civic_props_native.semantic.json"
SOURCE=PROJECT/"content/sprites/environment/props/meridian_civic/native"
RUNTIME=PROJECT/"content/sprites/environment/props/meridian_civic/runtime"
CATALOG=PROJECT/"game/world/levels/presentation/meridian_civic_native_prop_catalog.generated.gd"
CANVASES={
"meridian_civic_structure":(80,96),"meridian_civic_lighting":(64,96),"meridian_civic_signage":(80,112),"meridian_civic_terminal":(64,96),"meridian_civic_utility":(80,96),"meridian_civic_security":(64,96),"meridian_civic_bench":(144,80),"meridian_civic_waste":(48,80),"meridian_civic_traffic_control":(176,160),"meridian_civic_worksite":(64,160),"meridian_civic_floor_hardware":(96,96),"meridian_civic_industrial_module":(128,160),"meridian_civic_basin":(96,96),"meridian_civic_planter":(144,96),"meridian_civic_debris":(160,96),"meridian_civic_crate":(96,80),"meridian_civic_container":(80,80)}

def main():
 data=json.loads(MANIFEST.read_text()); catalog={}
 for e in data["entries"]:
  family=e["runtime_family"]; variant=e["variant_key"]; cw,ch=CANVASES[family]
  src=SOURCE/family/e["source_file"]
  with Image.open(src) as im: rgba=im.convert("RGBA")
  ax,ay=map(float,e["extract_anchor_px"]); mode=e["anchor_mode"]
  target=(cw/2,ch) if mode=="floor_contact" else (cw/2,ch/2)
  left=target[0]-ax; top=target[1]-ay
  if left!=int(left) or top!=int(top): raise RuntimeError(f"half-pixel padding for {family}/{variant}")
  left,top=int(left),int(top)
  if left<0 or top<0 or left+rgba.width>cw or top+rgba.height>ch: raise RuntimeError(f"canvas overflow {family}/{variant}: {(left,top,rgba.size)} in {(cw,ch)}")
  out=Image.new("RGBA",(cw,ch)); out.alpha_composite(rgba,(left,top)); dst=RUNTIME/family/f"{variant}.png"; dst.parent.mkdir(parents=True,exist_ok=True); out.save(dst,optimize=True)
  item=dict(e); item.update({"texture_path":f"res://{dst.relative_to(PROJECT).as_posix()}","canvas_size":[cw,ch],"sprite_position":[0,-ch/2] if mode=="floor_contact" else [0,0]})
  catalog[f"{family}/{variant}"]=item
 CATALOG.parent.mkdir(parents=True,exist_ok=True)
 payload=json.dumps(catalog,indent=2,sort_keys=True).replace("null","null")
 CATALOG.write_text("# Generated by build_lower_quarter_native_prop_runtime.py; do not edit.\nclass_name MeridianCivicNativePropCatalog\nextends RefCounted\n\nconst ENTRIES := "+payload+"\n")
 print(f"built {len(catalog)} variants in {len(CANVASES)} runtime families")
if __name__=="__main__": main()
