"""TUTORIAL command handler with detailed guidance."""


TOPIC_LINES = {
    "CORE": [
        "TUTORIAL > CORE",
        "MISSION: PRESERVE COMMAND AUTHORITY AND ARCHIVAL INTEGRITY.",
        "TIME CONTROL: THE WORLD ONLY ADVANCES ON TIME-BEARING COMMANDS.",
        "NO BACKGROUND TICKS: IF YOU DO NOT ISSUE TIME-BEARING COMMANDS, NOTHING MOVES.",
        "- WAIT / WAIT NX / WAIT UNTIL <ASSAULT|APPROACH|REPAIR_DONE> ADVANCE TIME.",
        "- SCAVENGE AND SCAVENGE NX ALSO ADVANCE TIME.",
        "WAIT UNITS: 5 TICKS OUTSIDE ASSAULT, 1 TICK DURING ACTIVE ASSAULT.",
        "READOUT LOOP: STATUS -> ONE DECISION -> WAIT -> REASSESS.",
        "RESOURCE TRIAD: MATERIALS, INVENTORY INPUTS, AND STOCK (AMMO/DRONES).",
        "POWER AND COMMS SET FIDELITY: LOWER FIDELITY MEANS LESS DETAIL AND SHORTER WARNINGS.",
        "FAILURE LATCHES: COMMAND CENTER LOST OR ARCHIVAL INTEGRITY LOST.",
        "POST-FAILURE: ONLY RESET OR REBOOT ACCEPTED.",
        "AUTHORITY SPLIT: COMMAND MODE ENABLES STRATEGIC CONTROL.",
    ],
    "MOVEMENT": [
        "TUTORIAL > MOVEMENT",
        "DEPLOY <TARGET> LEAVES COMMAND MODE AND STARTS TRANSIT.",
        "PRIMARY DEPLOY TARGETS: NORTH OR SOUTH TRANSIT NODES.",
        "FULL COMMS MAY AUTO-ROUTE TO A SECTOR VIA THE TRANSIT GRAPH.",
        "DEGRADED COMMS RESTRICT DEPLOYMENT TO NORTH OR SOUTH.",
        "MOVE <TARGET> TRAVELS BETWEEN CONNECTED LOCATIONS.",
        "RETURN RESTORES COMMAND AUTHORITY AFTER TRANSIT COMPLETES.",
        "TRADEOFF: FIELD MODE ENABLES RELAY STABILIZATION AND LOCAL REPAIRS.",
        "TRADEOFF: COMMAND MODE IS REQUIRED FOR POLICY, ALLOCATION, BUILD, AND DOCTRINE.",
        "ACTIVE TASKS BLOCK NEW ACTIONS UNTIL COMPLETION.",
        "WAIT ADVANCES TRAVEL AND TASK PROGRESS.",
        "FIELD WARNING DELAY: ASSAULT WARNINGS CAN ARRIVE LATE WHILE DEPLOYED.",
        "TRADEOFF: MOVEMENT COSTS TIME DURING A WINDOW WHEN ASSAULTS MAY TRIGGER.",
    ],
    "SYSTEMS": [
        "TUTORIAL > SYSTEMS",
        "FOCUS <SECTOR> BIASES ASSAULT TARGET SELECTION AWAY FROM THAT SECTOR.",
        "FOCUS IS IGNORED DURING ACTIVE ASSAULT.",
        "TRADEOFF: FOCUS PROTECTS ONE AREA BUT LEAVES OTHERS MORE LIKELY TO DRAW FIRE.",
        "HARDEN SHIFTS TO A SYSTEM-WIDE DEFENSIVE POSTURE AND CLEARS FOCUS.",
        "HARDEN IS IGNORED DURING ACTIVE ASSAULT.",
        "REPAIR <STRUCTURE> QUEUES A REPAIR; COSTS MATERIALS; COMPLETES OVER TIME.",
        "REMOTE REPAIR IS COMMAND-ONLY AND LIMITED TO DAMAGED STRUCTURES.",
        "LOCAL REPAIR IS FIELD-ONLY, FASTER, AND CHEAPER, BUT REQUIRES POWER AND PRESENCE.",
        "REPAIR <STRUCTURE> FULL RESTORES SECTOR STABILITY AT EXTRA COST.",
        "DESTROYED STRUCTURES REQUIRE LOCAL RECONSTRUCTION AND ARE BLOCKED DURING ASSAULT.",
        "SCAVENGE RUNS RECOVER MATERIALS BUT ADVANCE TIME AND THREAT.",
        "SCAVENGE RUNS TAKE 3 TICKS PER RUN AND YIELD 1-3 MATERIALS.",
    ],
    "GRID": [
        "TUTORIAL > GRID",
        "BUILD <TYPE> <X> <Y> PLACES A STRUCTURE IN THE CURRENT SECTOR GRID.",
        "COMMAND AUTHORITY REQUIRED. MATERIAL COSTS APPLY.",
        "BUILD USES CURRENT SECTOR CONTEXT AND WILL FAIL IF THE SECTOR IS INVALID.",
        "GRID IS 12X12 PER SECTOR; COORDINATES START AT (0,0).",
        "CELL MUST BE EMPTY; OUT-OF-BOUNDS OR OCCUPIED CELLS REJECTED.",
        "KNOWN TYPES: WALL, TURRET, GENERATOR.",
        "PERIMETER WALLS AND TOPOLOGY AFFECT ASSAULT PRESSURE.",
        "TRADEOFF: BUILDING CONSUMES MATERIALS NOW FOR DEFENSE OR POWER LATER.",
    ],
    "POLICY": [
        "TUTORIAL > POLICY",
        "SET REPAIR/DEFENSE/SURVEILLANCE 0-4 SETS GLOBAL SLIDERS.",
        "REPAIR INTENSITY INCREASES REPAIR SPEED BUT COSTS MORE MATERIALS AND POWER.",
        "DEFENSE READINESS INCREASES DEFENSE OUTPUT BUT INCREASES POWER DRAW AND WEAR.",
        "SURVEILLANCE COVERAGE SPEEDS DETECTION AND IMPROVES FIDELITY BUFFER AT POWER COST.",
        "LOWER LEVELS CONSERVE POWER BUT SLOW RECOVERY OR DETECTION.",
        "SET FAB <CAT> 0-4 BIASES AMBIENT FABRICATION OUTPUT.",
        "POLICY PRESET <BALANCED|SIEGE|RECOVERY|LOW_POWER> APPLIES A BASELINE.",
        "POLICY SHOW REPORTS CURRENT SLIDERS.",
        "POLICY DRONE_REPAIR <AUTO|OFF> CONTROLS AUTONOMOUS PERIMETER REPAIR.",
        "FORTIFY <SECTOR> 0-4 RAISES SECTOR RESILIENCE AND PERIMETER WALL STRENGTH.",
        "FORTIFY INCREASES POWER LOAD AND CAN SLOW OTHER SYSTEM THROUGHPUT.",
        "FORTIFY T_NORTH|T_SOUTH 0-4 IMPROVES TRANSIT INTERCEPTION.",
        "CONFIG DOCTRINE <NAME> SHIFTS DEFENSE PRIORITIES AND THREAT PROFILE.",
        "DOCTRINES: BALANCED, AGGRESSIVE, COMMAND_FIRST, INFRASTRUCTURE_FIRST, SENSOR_PRIORITY.",
        "ALLOCATE DEFENSE <SECTOR|GROUP> <PERCENT> BIASES DEFENSE ROUTING.",
        "GROUPS: COMMAND, POWER, SENSORS, PERIMETER.",
    ],
    "FABRICATION": [
        "TUTORIAL > FABRICATION",
        "FAB ADD <ITEM> QUEUES A FAB JOB; PRODUCTION ADVANCES WITH TIME.",
        "FAB QUEUE SHOWS JOBS AND REMAINING TICKS.",
        "FAB CANCEL <ID> REMOVES A JOB.",
        "FAB PRIORITY <CATEGORY> REORDERS QUEUE BY CATEGORY.",
        "FAB JOBS CONSUME INVENTORY INPUTS (SCRAP, COMPONENTS, ASSEMBLIES).",
        "AMBIENT FABRICATION RUNS EACH TICK BASED ON FAB ALLOCATION LEVELS.",
        "FABRICATION OUTPUT DEPENDS ON POWER, LOGISTICS LOAD, AND POLICY ALLOCATION.",
        "OUTPUTS INCLUDE TURRET AMMO, REPAIR DRONES, COMPONENTS, AND ARCHIVE ARMOR.",
        "TRADEOFF: HEAVY FAB LOAD SLOWS REPAIR AND RECOVERY UNDER STRESS.",
        "STOCK OUTPUTS FEED DRONE AND TURRET CONSUMPTION DURING ASSAULT.",
    ],
    "ASSAULT": [
        "TUTORIAL > ASSAULT",
        "APPROACHES SPAWN AND MOVE THROUGH TRANSIT LANES BEFORE ENGAGEMENT.",
        "STATUS ASSAULT AND STATUS FULL SHOW ETA, ROUTES, AND ACTIVE PRESSURE.",
        "TRANSIT INTERCEPTS CONSUME TURRET AMMO BEFORE DIRECT ENGAGEMENT.",
        "PERIMETER CONTINUITY REDUCES PRESSURE; WEAK SEGMENTS AMPLIFY DAMAGE.",
        "TACTICAL COMMANDS REQUIRE ACTIVE ASSAULT:",
        "- REROUTE POWER <SECTOR> BOOSTS POWER FOR 2 TICKS.",
        "- BOOST DEFENSE <SECTOR> BOOSTS MITIGATION FOR 2 TICKS.",
        "- DRONE DEPLOY <SECTOR> CONSUMES REPAIR DRONE STOCK.",
        "- LOCKDOWN <SECTOR> ISOLATES DAMAGE FOR 2 TICKS.",
        "- PRIORITIZE REPAIR <SECTOR> BOOSTS REPAIR FOR 3 TICKS.",
        "TRADEOFF: TACTICAL BUFFS ARE SHORT AND COMPETE FOR LIMITED RESOURCES.",
        "ASSAULTS SLOW REPAIR SPEED AND CAN DAMAGE STRUCTURES OVER MULTIPLE TICKS.",
        "FOCUS AND HARDEN COMMANDS ARE IGNORED DURING ACTIVE ASSAULT.",
        "RELAY OPERATIONS:",
        "- SCAN RELAYS FROM COMMAND TO LOCATE UNSTABLE RELAYS.",
        "- STABILIZE RELAY <ID> IN FIELD MODE AT THE RELAY SECTOR.",
        "- SYNC BACK IN COMMAND TO CONVERT PACKETS INTO KNOWLEDGE BENEFITS.",
        "TRADEOFF: RELAY RUNS COST TIME AND REMOVE COMMAND AUTHORITY.",
    ],
    "STATUS": [
        "TUTORIAL > STATUS",
        "STATUS IS YOUR PRIMARY SENSOR GRID.",
        "STATUS (BRIEF) SHOWS TIME, THREAT, ASSAULT TIMER, AND SECTOR ROWS.",
        "STATUS FULL ADDS DIAGNOSTICS: POWER, FIDELITY, PERIMETER TOPOLOGY, QUEUES.",
        "STATUS FAB/POSTURE/ASSAULT/POLICY/SYSTEMS/RELAY FOCUS ON SUBSYSTEMS.",
        "COMMS FIDELITY REDUCES DETAIL AND PRECISION WHEN DEGRADED.",
        "OPERATOR LOOP: STATUS -> ONE CHANGE -> WAIT -> REASSESS.",
        "WHEN CONFUSED, RUN STATUS FULL THEN HELP OR TUTORIAL TOPICS.",
    ],
}


def _tutorial_index() -> list[str]:
    return [
        "TUTORIAL INDEX",
        "USE: TUTORIAL <TOPIC>",
        "TOPICS: CORE | MOVEMENT | SYSTEMS | GRID | POLICY | FABRICATION | ASSAULT | STATUS",
        "TIP: COMMANDS ACCEPT OPTIONAL LEADING '/' (EXAMPLE: /TUTORIAL CORE).",
        "",
        "[CORE] SESSION GOALS, TIME CONTROL, FAILURE STATES",
        "[MOVEMENT] COMMAND VS FIELD AUTHORITY AND TRANSIT",
        "[SYSTEMS] FOCUS, HARDEN, REPAIR, SCAVENGE",
        "[GRID] BUILDING, COORDINATES, STRUCTURE COSTS",
        "[POLICY] SLIDERS, FORTIFICATION, DOCTRINE, ALLOCATION",
        "[FABRICATION] QUEUES, PRIORITIES, OUTPUT TRADEOFFS",
        "[ASSAULT] TACTICAL COMMANDS AND RELAY OPERATIONS",
        "[STATUS] SENSOR READOUTS AND DIAGNOSTICS",
    ]


def cmd_tutorial(topic: str | None = None) -> list[str]:
    """Return tutorial index or topic details."""

    if not topic:
        return _tutorial_index()

    key = topic.strip().upper()
    lines = TOPIC_LINES.get(key)
    if lines:
        return lines
    return [
        "UNKNOWN TUTORIAL TOPIC.",
        "USE: TUTORIAL <TOPIC>",
        "TOPICS: CORE | MOVEMENT | SYSTEMS | GRID | POLICY | FABRICATION | ASSAULT | STATUS",
    ]
