#!/usr/bin/env python3
"""
Render a source-proportioned Sundered Keep causeway reconstruction from extracted tiles.

This is an art/layout preview tool. It consumes the extraction manifest generated by
extract_sundered_keep_causeway_design_tiles.py and composes a deterministic PNG that
matches the broad layout of the master sheet without copying the master image itself.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable

from PIL import Image, ImageDraw


TILE = 32
LAYERS = {
    "TerrainBase": 0,
    "FloorDetail": 10,
    "TerrainEdges": 20,
    "Traversal": 25,
    "WallsHigh": 30,
    "PropsStatic": 40,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a Sundered Keep causeway layout reconstruction from extracted tiles."
    )
    parser.add_argument(
        "--extract-root",
        type=Path,
        default=Path("content/tiles/sundered_keep/causeway_design_extract"),
        help="Root directory produced by the causeway extraction script.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Optional explicit extraction manifest path.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output PNG path. Defaults to reports/causeway_design_reconstruction.png.",
    )
    parser.add_argument(
        "--debug-grid",
        action="store_true",
        help="Draw a faint 32px grid over the reconstruction.",
    )
    return parser.parse_args()


def load_assets(extract_root: Path, manifest_path: Path) -> dict[str, Image.Image]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assets: dict[str, Image.Image] = {}
    for record in manifest["assets"]:
        texture_path = extract_root / record["texture"]
        assets[record["id"]] = Image.open(texture_path).convert("RGBA")
    return assets


def paste(canvas: Image.Image, assets: dict[str, Image.Image], asset_id: str, x: int, y: int) -> None:
    tile = assets[asset_id]
    canvas.alpha_composite(tile, (x * TILE, y * TILE))


def fill_rect(
    canvas: Image.Image,
    assets: dict[str, Image.Image],
    asset_ids: Iterable[str],
    x: int,
    y: int,
    w: int,
    h: int,
) -> None:
    ids = list(asset_ids)
    for yy in range(y, y + h):
        for xx in range(x, x + w):
            asset_id = ids[(xx * 7 + yy * 11) % len(ids)]
            paste(canvas, assets, asset_id, xx, yy)


def repeat(
    canvas: Image.Image,
    assets: dict[str, Image.Image],
    asset_id: str,
    start: tuple[int, int],
    count: int,
    step: tuple[int, int],
) -> None:
    x, y = start
    dx, dy = step
    for index in range(count):
        paste(canvas, assets, asset_id, x + dx * index, y + dy * index)


def draw_grid(canvas: Image.Image) -> None:
    draw = ImageDraw.Draw(canvas)
    color = (255, 255, 255, 24)
    for x in range(0, canvas.width, TILE):
        draw.line((x, 0, x, canvas.height), fill=color)
    for y in range(0, canvas.height, TILE):
        draw.line((0, y, canvas.width, y), fill=color)


def render_reconstruction(assets: dict[str, Image.Image], debug_grid: bool) -> Image.Image:
    canvas_tiles = (45, 34)
    canvas = Image.new("RGBA", (canvas_tiles[0] * TILE, canvas_tiles[1] * TILE), (0, 0, 0, 0))

    water_variants = ["sundered_water_dark_01", "sundered_water_ripple_01"]
    causeway_floor = [
        "causeway_floor_center_01",
        "causeway_floor_center_worn_01",
        "causeway_floor_center_dark_01",
        "causeway_floor_cracked_01",
    ]
    landing_floor = ["outer_landing_floor_center_01", "outer_landing_floor_dark_01"]
    forecourt_floor = ["forecourt_floor_center_01", "forecourt_floor_variant_01"]

    fill_rect(canvas, assets, water_variants, 0, 0, 45, 34)

    # Upper keep mass: broad wall/forecourt band across the top of the master.
    fill_rect(canvas, assets, forecourt_floor, 6, 0, 33, 3)
    fill_rect(canvas, assets, forecourt_floor, 5, 3, 35, 5)
    fill_rect(canvas, assets, forecourt_floor, 0, 4, 5, 5)
    fill_rect(canvas, assets, forecourt_floor, 40, 4, 5, 5)
    repeat(canvas, assets, "rampart_crenellation_s_01", (0, 3), 5, (3, 0))
    repeat(canvas, assets, "rampart_crenellation_s_01", (30, 3), 5, (3, 0))
    repeat(canvas, assets, "rampart_wall_horizontal_01", (6, 7), 4, (3, 0))
    repeat(canvas, assets, "rampart_wall_horizontal_01", (27, 7), 4, (3, 0))
    paste(canvas, assets, "rampart_corner_chunk_01", 2, 1)
    paste(canvas, assets, "rampart_corner_chunk_01", 38, 1)
    paste(canvas, assets, "metal_grate_floor_01", 8, 0)
    paste(canvas, assets, "metal_grate_floor_01", 34, 0)
    paste(canvas, assets, "rubble_pile_01", 10, 5)
    paste(canvas, assets, "rubble_pile_01", 32, 5)
    paste(canvas, assets, "gothic_torch_post_01", 18, 4)
    paste(canvas, assets, "gothic_torch_post_01", 26, 4)

    # Gatehouse throat and stair transition.
    fill_rect(canvas, assets, ["gatehouse_entry_floor_01"], 19, 6, 7, 2)
    paste(canvas, assets, "gatehouse_wall_face_01", 16, 7)
    paste(canvas, assets, "gatehouse_wall_face_alt_01", 26, 7)
    paste(canvas, assets, "gatehouse_side_pillar_w_01", 15, 8)
    paste(canvas, assets, "gatehouse_side_pillar_e_01", 27, 8)
    paste(canvas, assets, "gatehouse_steps_n_01", 20, 8)
    fill_rect(canvas, assets, ["gatehouse_threshold_floor_01"], 20, 9, 5, 2)

    # Long central causeway.
    fill_rect(canvas, assets, causeway_floor, 20, 10, 5, 19)
    repeat(canvas, assets, "causeway_edge_w_01", (19, 10), 10, (0, 2))
    repeat(canvas, assets, "causeway_edge_e_01", (25, 10), 10, (0, 2))
    paste(canvas, assets, "causeway_edge_w_broken_01", 19, 24)
    paste(canvas, assets, "causeway_edge_e_broken_01", 25, 24)

    for y in (14, 18, 22, 26):
        paste(canvas, assets, "causeway_buttress_w_01", 17, y)
        paste(canvas, assets, "causeway_buttress_e_01", 26, y)
    for y in (12, 17, 21, 25):
        paste(canvas, assets, "causeway_parapet_post_01", 19, y)
        paste(canvas, assets, "causeway_parapet_post_01", 25, y)

    # Lower landing and mooring details.
    fill_rect(canvas, assets, landing_floor, 15, 28, 15, 6)
    paste(canvas, assets, "outer_landing_edge_n_01", 17, 28)
    paste(canvas, assets, "outer_landing_edge_n_01", 24, 28)
    paste(canvas, assets, "outer_landing_corner_nw_01", 15, 28)
    paste(canvas, assets, "outer_landing_corner_ne_01", 28, 28)
    repeat(canvas, assets, "outer_landing_edge_w_01", (15, 29), 2, (0, 3))
    repeat(canvas, assets, "outer_landing_edge_e_01", (30, 29), 2, (0, 3))
    paste(canvas, assets, "causeway_lower_side_tower_w_01", 16, 28)
    paste(canvas, assets, "causeway_lower_side_tower_e_01", 27, 28)
    paste(canvas, assets, "mooring_bollards_w_01", 14, 29)
    paste(canvas, assets, "mooring_bollards_e_01", 30, 29)
    paste(canvas, assets, "mooring_ring_w_01", 19, 29)
    paste(canvas, assets, "mooring_ring_e_01", 25, 29)
    paste(canvas, assets, "landing_grate_01", 16, 31)
    paste(canvas, assets, "landing_grate_01", 28, 31)

    # Marker posts in the water mirror the master sheet's receding channel markers.
    for x, y in ((3, 13), (5, 16), (7, 20), (9, 24), (11, 27), (13, 30)):
        paste(canvas, assets, "sundered_water_marker_post_01", x, y)
    for x, y in ((41, 13), (39, 16), (37, 20), (35, 24), (33, 27), (31, 30)):
        paste(canvas, assets, "sundered_water_marker_post_01", x, y)

    if debug_grid:
        draw_grid(canvas)

    return canvas


def main() -> int:
    args = parse_args()
    extract_root = args.extract_root.expanduser().resolve()
    manifest_path = (
        args.manifest.expanduser().resolve()
        if args.manifest
        else extract_root / "reports" / "sundered_keep_causeway_design_extract.game32.json"
    )
    out_path = (
        args.out.expanduser().resolve()
        if args.out
        else extract_root / "reports" / "causeway_design_reconstruction.png"
    )

    if not manifest_path.exists():
        print(f"ERROR: manifest not found: {manifest_path}")
        return 2

    assets = load_assets(extract_root, manifest_path)
    missing = sorted(
        required
        for required in (
            "sundered_water_dark_01",
            "sundered_water_ripple_01",
            "causeway_floor_center_01",
            "outer_landing_floor_center_01",
            "forecourt_floor_center_01",
        )
        if required not in assets
    )
    if missing:
        print(f"ERROR: required assets missing from manifest: {', '.join(missing)}")
        return 3

    out_path.parent.mkdir(parents=True, exist_ok=True)
    image = render_reconstruction(assets, args.debug_grid)
    image.save(out_path)

    print(f"manifest:       {manifest_path}")
    print(f"extract root:   {extract_root}")
    print(f"reconstruction: {out_path}")
    print(f"size:           {image.width}x{image.height}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
