# Generated by extract_sundered_keep_assets.py
# Load the full metadata JSON at MANIFEST_PATH.

extends RefCounted

const MANIFEST_PATH := "res://content/metadata/game32/sundered_keep.game32.json"

static func load_manifest() -> Dictionary:
	var file := FileAccess.open(MANIFEST_PATH, FileAccess.READ)
	if file == null:
		push_error("Could not open Sundered Keep Game32 manifest: " + MANIFEST_PATH)
		return {}
	var parsed = JSON.parse_string(file.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("Invalid Sundered Keep Game32 manifest JSON: " + MANIFEST_PATH)
		return {}
	return parsed
