#!/usr/bin/env python3
"""Render a quick preview sheet from a terrain mapping JSON."""

from __future__ import annotations

import argparse
import json
import math
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate a terrain mapping JSON and render classified cells/stamps as a contact sheet."
    )
    parser.add_argument("mapping", type=Path, help="Mapping JSON generated by classify_terrain_cells.py.")
    parser.add_argument("-o", "--out", type=Path, default=None, help="Output preview PNG path.")
    parser.add_argument("--scale", type=int, default=4, help="Preview scale multiplier.")
    parser.add_argument("--columns", type=int, default=4, help="Number of preview columns.")
    return parser.parse_args()


def require_tool(name: str) -> str:
    path = shutil.which(name)
    if path is None:
        raise SystemExit(f"Required tool not found: {name}")
    return path


def resolve_source_image(mapping_path: Path, source_image: str) -> Path:
    source = Path(source_image)
    if source.exists():
        return source

    candidates = [
        mapping_path.parent / source,
        Path.cwd() / source,
        Path.cwd() / "custodian" / source,
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise SystemExit(f"Source image not found: {source_image}")


def load_mapping(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def has_control_characters(value: Any) -> list[str]:
    bad: list[str] = []

    def walk(obj: Any, trail: str) -> None:
        if isinstance(obj, dict):
            for key, child in obj.items():
                walk(child, f"{trail}.{key}" if trail else str(key))
        elif isinstance(obj, list):
            for index, child in enumerate(obj):
                walk(child, f"{trail}[{index}]")
        elif isinstance(obj, str) and any(ord(char) < 32 for char in obj):
            bad.append(trail)

    walk(value, "")
    return bad


def validate_mapping(data: dict[str, Any]) -> list[str]:
    issues: list[str] = []
    stamps = data.get("stamps", {})
    for key, cell in data.get("cells", {}).items():
        for field in ("coord", "source_rect", "terrain_type", "walkable", "collision"):
            if field not in cell:
                issues.append(f"cell {key} missing {field}")
        owner = cell.get("stamp_owner")
        if owner is not None and owner not in stamps:
            issues.append(f"cell {key} references missing stamp {owner}")
    for stamp_id, stamp in stamps.items():
        for field in ("coord", "source_rect", "size_cells", "terrain_type"):
            if field not in stamp:
                issues.append(f"stamp {stamp_id} missing {field}")
    for trail in has_control_characters(data):
        issues.append(f"control character in {trail}")
    return issues


def preview_entries(data: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    entries: list[tuple[str, dict[str, Any]]] = []
    for stamp_id, stamp in sorted(data.get("stamps", {}).items()):
        entries.append((f"stamp {stamp_id}", stamp))
    for key, cell in sorted(data.get("cells", {}).items(), key=lambda item: tuple(item[1].get("coord", [9999, 9999]))):
        if cell.get("terrain_type") in {"stamp_origin", "stamp_member"}:
            continue
        entries.append((f"cell {key}", cell))
    return entries


def draw_crop(
    magick: str,
    source_image: Path,
    out_path: Path,
    label: str,
    entry: dict[str, Any],
    scale: int,
) -> None:
    x, y, width, height = entry["source_rect"]
    scaled_width = width * scale
    scaled_height = height * scale
    cmd = [
        magick,
        str(source_image),
        "-crop",
        f"{width}x{height}+{x}+{y}",
        "+repage",
        "-filter",
        "point",
        "-resize",
        f"{scaled_width}x{scaled_height}",
        "-stroke",
        "red",
        "-strokewidth",
        "4",
        "-fill",
        "none",
        "-draw",
        f"rectangle 0,0 {scaled_width - 1},{scaled_height - 1}",
    ]
    bounds = entry.get("opaque_bounds_px")
    if bounds is not None:
        bounds_x, bounds_y, bounds_width, bounds_height = bounds
        cmd.extend(
            [
                "-stroke",
                "lime",
                "-strokewidth",
                "3",
                "-fill",
                "none",
                "-draw",
                (
                    f"rectangle {bounds_x * scale},{bounds_y * scale} "
                    f"{(bounds_x + bounds_width) * scale - 1},{(bounds_y + bounds_height) * scale - 1}"
                ),
            ]
        )
    label_text = f"{label}\\n{entry.get('terrain_type', '?')} coll={entry.get('collision', '?')}"
    cmd.extend(["-background", "#202020", "-fill", "white", "-gravity", "south", "-splice", "0x42", "-annotate", "+0+6", label_text])
    cmd.append(str(out_path))
    subprocess.run(cmd, check=True)


def render_preview(mapping_path: Path, data: dict[str, Any], source_image: Path, out_path: Path, scale: int, columns: int) -> None:
    magick = require_tool("magick")
    entries = preview_entries(data)
    if not entries:
        raise SystemExit("No classified cells or stamps to preview.")

    with tempfile.TemporaryDirectory(prefix="custodian_mapping_preview_") as tmp_dir:
        tmp = Path(tmp_dir)
        crop_paths: list[Path] = []
        for index, (label, entry) in enumerate(entries):
            crop_path = tmp / f"{index:04d}.png"
            draw_crop(magick, source_image, crop_path, label, entry, max(1, scale))
            crop_paths.append(crop_path)

        rows = math.ceil(len(crop_paths) / max(1, columns))
        subprocess.run(
            [
                magick,
                "montage",
                *[str(path) for path in crop_paths],
                "-tile",
                f"{columns}x{rows}",
                "-geometry",
                "+8+8",
                "-background",
                "#101010",
                str(out_path),
            ],
            check=True,
        )


def main() -> int:
    args = parse_args()
    if not args.mapping.exists():
        print(f"Mapping not found: {args.mapping}", file=sys.stderr)
        return 2

    data = load_mapping(args.mapping)
    source_image = resolve_source_image(args.mapping, data["source_image"])
    out_path = args.out or args.mapping.with_name(f"{args.mapping.stem}.preview.png")
    issues = validate_mapping(data)

    print(f"mapping: {args.mapping}")
    print(f"source: {source_image}")
    print(f"cells: {len(data.get('cells', {}))}")
    print(f"stamps: {len(data.get('stamps', {}))}")
    if issues:
        print("issues:")
        for issue in issues:
            print(f"  - {issue}")
    else:
        print("issues: none")

    render_preview(args.mapping, data, source_image, out_path, args.scale, args.columns)
    print(f"preview: {out_path}")
    return 1 if issues else 0


if __name__ == "__main__":
    raise SystemExit(main())
