#!/usr/bin/env python3
"""
fix_transparent_runtime_assets.py

Consumes the transparent_padding_report.csv generated by the audit script and applies
safe runtime asset normalization actions.

Default behavior is DRY RUN.

Recommended usage:

  cd ~/Projects/CUSTODIAN/custodian

  python tools/fix_transparent_runtime_assets.py \
    --root . \
    --csv reports/transparent_padding_report.csv

  python tools/fix_transparent_runtime_assets.py \
    --root . \
    --csv reports/transparent_padding_report.csv \
    --apply

What it does safely:
  - Skips sprite sheets / animation sheets by default.
  - Pads assets whose canvas is not a 32px multiple.
  - Trims excessive transparent bounds for safe non-sprite runtime assets.
  - Re-centers / bottom-anchors visible art onto a tile-grid canvas.
  - Backs up every modified PNG.
  - Writes a JSONL manifest.

What it does NOT do by default:
  - It does not rewrite operator/enemy animation sheets.
  - It does not crop fixed-frame sprite sheets like __5f__96.
  - It does not edit Godot .tres/.tscn files.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import shutil
import sys
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    from PIL import Image
except ImportError:
    print("Missing dependency: Pillow", file=sys.stderr)
    print("Install with: python -m pip install pillow", file=sys.stderr)
    raise


FRAME_HINT_RE = re.compile(
    r"__(?P<frames>\d+)f__(?P<size>\d+)(?:\.png)?$", re.IGNORECASE
)
ANIM_NAME_RE = re.compile(
    r"(?:^|[_\-])(idle|walk|run|attack|fast|heavy|light|stance|fire|loop|windup|recovery|hitreact|death|sheet)(?:[_\-]|$)",
    re.IGNORECASE,
)
DEFAULT_EXCLUDE_SUBSTRINGS = [
    "_extraction_review/",
    "/masters/",
    "/source/",
    "/raw/",
    "_detected_bboxes",
]


@dataclass
class FixAction:
    path: str
    action: str
    reason: str
    old_size: tuple[int, int]
    new_size: tuple[int, int]
    visible_bbox: Optional[tuple[int, int, int, int]]
    paste_xy: tuple[int, int]
    backup_path: Optional[str]
    old_sha256: Optional[str]
    new_sha256: Optional[str]
    applied: bool
    skipped: bool
    skip_reason: str


def boolish(value: str) -> bool:
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def intish(value: str, default: int = 0) -> int:
    try:
        if value is None or value == "":
            return default
        return int(float(value))
    except ValueError:
        return default


def floatish(value: str, default: float = 0.0) -> float:
    try:
        if value is None or value == "":
            return default
        return float(value)
    except ValueError:
        return default


def ceil_to_multiple(value: int, multiple: int) -> int:
    if value <= 0:
        return multiple
    return ((value + multiple - 1) // multiple) * multiple


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def is_runtime_asset(rel_path: str) -> bool:
    parts = Path(rel_path).parts
    return "runtime" in {p.lower() for p in parts}


def is_probably_sprite_or_sheet(row: dict[str, str]) -> bool:
    rel_path = row.get("path", "")
    filename = row.get("filename", Path(rel_path).name)

    lower_path = rel_path.lower()
    lower_name = filename.lower()

    if lower_path.startswith("sprites/"):
        return True

    if FRAME_HINT_RE.search(filename):
        return True

    if "__body__" in lower_name or "__fx__" in lower_name or "__weapon__" in lower_name:
        return True

    if ANIM_NAME_RE.search(filename):
        return True

    canvas_w = intish(row.get("canvas_w"))
    canvas_h = intish(row.get("canvas_h"))

    # Very wide, short images are usually sprite strips or FX strips.
    if canvas_h in {48, 64, 96, 128} and canvas_w >= canvas_h * 4:
        return True

    return False


def resolve_asset_path(root: Path, rel_path: str) -> Path:
    raw = Path(rel_path)

    if raw.is_absolute():
        return raw

    candidate = root / raw
    if candidate.exists():
        return candidate

    # Most audit runs use --root content, while this fixer often uses --root repo.
    content_candidate = root / "content" / raw
    if content_candidate.exists():
        return content_candidate

    return candidate


def get_visible_bbox(
    img: Image.Image, alpha_threshold: int
) -> Optional[tuple[int, int, int, int]]:
    rgba = img.convert("RGBA")
    alpha = rgba.getchannel("A")
    mask = alpha.point(lambda a: 255 if a > alpha_threshold else 0)
    return mask.getbbox()


def choose_action(
    row: dict[str, str],
    allow_sprites: bool,
    fix_non_runtime: bool,
    min_margin_px: int,
    min_bbox_empty_pct: float,
) -> tuple[str, str]:
    rel_path = row.get("path", "")
    issues = row.get("issues", "")
    suspicious = boolish(row.get("suspicious", "false"))

    if not suspicious:
        return "skip", "not suspicious"

    if not fix_non_runtime and not is_runtime_asset(rel_path):
        return "skip", "not a runtime path"

    if is_probably_sprite_or_sheet(row) and not allow_sprites:
        return "skip", "sprite or animation sheet skipped by default"

    canvas_w = intish(row.get("canvas_w"))
    canvas_h = intish(row.get("canvas_h"))
    suggested_w = intish(row.get("suggested_trim_canvas_w"))
    suggested_h = intish(row.get("suggested_trim_canvas_h"))
    max_margin = intish(row.get("max_margin_px"))
    bbox_empty_pct = floatish(row.get("bbox_empty_pct"))

    if canvas_w <= 0 or canvas_h <= 0:
        return "skip", "invalid canvas dimensions"

    if "FULLY_TRANSPARENT" in issues:
        return "skip", "fully transparent asset; needs manual review"

    if "CANVAS_NOT_MULTIPLE_OF_TILE" in issues:
        return "pad_to_tile_grid", "canvas is not tile-grid aligned"

    can_shrink = (
        suggested_w > 0
        and suggested_h > 0
        and (suggested_w < canvas_w or suggested_h < canvas_h)
    )

    if (
        can_shrink
        and max_margin >= min_margin_px
        and bbox_empty_pct >= min_bbox_empty_pct
    ):
        return (
            "trim_to_tile_grid",
            "large transparent margin and recommended trim is smaller",
        )

    return "skip", "flagged but not safe enough for automatic modification"


def normalize_image(
    src_path: Path,
    action: str,
    tile_size: int,
    alpha_threshold: int,
    anchor: str,
) -> tuple[Image.Image, Optional[tuple[int, int, int, int]], tuple[int, int]]:
    with Image.open(src_path) as img:
        img = img.convert("RGBA")
        old_w, old_h = img.size

        bbox = get_visible_bbox(img, alpha_threshold)

        if bbox is None:
            raise ValueError("image is fully transparent")

        left, top, right, bottom = bbox
        visible = img.crop(bbox)
        visible_w, visible_h = visible.size

        if action == "pad_to_tile_grid":
            new_w = ceil_to_multiple(old_w, tile_size)
            new_h = ceil_to_multiple(old_h, tile_size)

            new_img = Image.new("RGBA", (new_w, new_h), (0, 0, 0, 0))

            # Preserve current origin for pure padding.
            paste_x = 0
            paste_y = 0
            new_img.paste(img, (paste_x, paste_y))
            return new_img, bbox, (paste_x, paste_y)

        if action == "trim_to_tile_grid":
            new_w = ceil_to_multiple(visible_w, tile_size)
            new_h = ceil_to_multiple(visible_h, tile_size)

            new_img = Image.new("RGBA", (new_w, new_h), (0, 0, 0, 0))

            if anchor == "top_left":
                paste_x = 0
                paste_y = 0
            elif anchor == "center":
                paste_x = (new_w - visible_w) // 2
                paste_y = (new_h - visible_h) // 2
            elif anchor == "bottom_center":
                paste_x = (new_w - visible_w) // 2
                paste_y = new_h - visible_h
            else:
                raise ValueError(f"unknown anchor: {anchor}")

            new_img.paste(visible, (paste_x, paste_y))
            return new_img, bbox, (paste_x, paste_y)

        raise ValueError(f"unknown action: {action}")


def backup_file(src_path: Path, root: Path, backup_root: Path) -> Path:
    try:
        rel = src_path.relative_to(root)
    except ValueError:
        rel = Path(src_path.name)

    dst = backup_root / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src_path, dst)
    return dst


def load_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        return list(reader)


def write_manifest_line(path: Path, action: FixAction) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(asdict(action), sort_keys=True) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Apply safe recommended fixes from transparent runtime asset audit CSV."
    )

    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Repo root or content root. Default: current directory.",
    )
    parser.add_argument(
        "--csv",
        type=Path,
        required=True,
        help="Path to transparent_padding_report.csv.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually modify files. Without this, runs dry-run only.",
    )
    parser.add_argument(
        "--allow-sprites",
        action="store_true",
        help="Allow modifying sprites/animation sheets. Dangerous. Default: false.",
    )
    parser.add_argument(
        "--fix-non-runtime",
        action="store_true",
        help="Allow modifying files whose path does not include /runtime/. Default: false.",
    )
    parser.add_argument(
        "--tile-size",
        type=int,
        default=32,
        help="Grid size. Default: 32.",
    )
    parser.add_argument(
        "--alpha-threshold",
        type=int,
        default=0,
        help="Alpha <= this value is treated as transparent. Default: 0.",
    )
    parser.add_argument(
        "--min-margin-px",
        type=int,
        default=32,
        help="Minimum transparent margin for automatic trimming. Default: 32.",
    )
    parser.add_argument(
        "--min-bbox-empty-pct",
        type=float,
        default=0.45,
        help="Minimum bbox empty percentage for automatic trimming. Default: 0.45.",
    )
    parser.add_argument(
        "--anchor",
        choices=["top_left", "center", "bottom_center"],
        default="bottom_center",
        help="How trimmed visible art is placed onto the new tile-grid canvas. Default: bottom_center.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("reports/fix_transparent_runtime_assets_manifest.jsonl"),
        help="JSONL manifest output path.",
    )

    args = parser.parse_args()

    root = args.root.expanduser().resolve()
    csv_path = args.csv.expanduser().resolve()
    manifest_path = (
        (root / args.manifest).resolve()
        if not args.manifest.is_absolute()
        else args.manifest.expanduser().resolve()
    )

    if not root.exists():
        print(f"Root does not exist: {root}", file=sys.stderr)
        return 1

    if not csv_path.exists():
        print(f"CSV does not exist: {csv_path}", file=sys.stderr)
        return 1

    rows = load_rows(csv_path)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_root = root / "_asset_fix_backups" / timestamp

    stats = {
        "rows": 0,
        "missing": 0,
        "skipped": 0,
        "would_apply": 0,
        "applied": 0,
        "errors": 0,
    }

    print()
    print("Mode:", "APPLY" if args.apply else "DRY RUN")
    print("Root:", root)
    print("CSV:", csv_path)
    print("Manifest:", manifest_path)
    if args.apply:
        print("Backup root:", backup_root)
    print()

    for row in rows:
        stats["rows"] += 1

        rel_path = row.get("path", "")
        src_path = resolve_asset_path(root, rel_path)

        action_name, reason = choose_action(
            row=row,
            allow_sprites=args.allow_sprites,
            fix_non_runtime=args.fix_non_runtime,
            min_margin_px=args.min_margin_px,
            min_bbox_empty_pct=args.min_bbox_empty_pct,
        )

        if not src_path.exists():
            stats["missing"] += 1
            fix_action = FixAction(
                path=rel_path,
                action="missing",
                reason="file does not exist",
                old_size=(intish(row.get("canvas_w")), intish(row.get("canvas_h"))),
                new_size=(0, 0),
                visible_bbox=None,
                paste_xy=(0, 0),
                backup_path=None,
                old_sha256=None,
                new_sha256=None,
                applied=False,
                skipped=True,
                skip_reason="file does not exist",
            )
            write_manifest_line(manifest_path, fix_action)
            continue

        if action_name == "skip":
            stats["skipped"] += 1
            fix_action = FixAction(
                path=rel_path,
                action="skip",
                reason=reason,
                old_size=(intish(row.get("canvas_w")), intish(row.get("canvas_h"))),
                new_size=(intish(row.get("canvas_w")), intish(row.get("canvas_h"))),
                visible_bbox=(
                    intish(row.get("visible_left")),
                    intish(row.get("visible_top")),
                    intish(row.get("visible_right_exclusive")),
                    intish(row.get("visible_bottom_exclusive")),
                ),
                paste_xy=(0, 0),
                backup_path=None,
                old_sha256=None,
                new_sha256=None,
                applied=False,
                skipped=True,
                skip_reason=reason,
            )
            write_manifest_line(manifest_path, fix_action)
            continue

        try:
            old_hash = sha256_file(src_path)

            with Image.open(src_path) as old_img:
                old_img = old_img.convert("RGBA")
                old_size = old_img.size

            new_img, bbox, paste_xy = normalize_image(
                src_path=src_path,
                action=action_name,
                tile_size=args.tile_size,
                alpha_threshold=args.alpha_threshold,
                anchor=args.anchor,
            )

            new_size = new_img.size

            # Do not rewrite if no size change happened.
            if new_size == old_size:
                stats["skipped"] += 1
                fix_action = FixAction(
                    path=rel_path,
                    action="skip",
                    reason=f"{action_name} produced no size change",
                    old_size=old_size,
                    new_size=new_size,
                    visible_bbox=bbox,
                    paste_xy=paste_xy,
                    backup_path=None,
                    old_sha256=old_hash,
                    new_sha256=old_hash,
                    applied=False,
                    skipped=True,
                    skip_reason="no size change",
                )
                write_manifest_line(manifest_path, fix_action)
                continue

            normalized_rel = rel_path.replace("\\", "/").lower()

            if any(token in normalized_rel for token in DEFAULT_EXCLUDE_SUBSTRINGS):
                stats["skipped"] += 1
                fix_action = FixAction(
                    path=rel_path,
                    action="skip",
                    reason="excluded review/source/raw asset",
                    old_size=(intish(row.get("canvas_w")), intish(row.get("canvas_h"))),
                    new_size=(intish(row.get("canvas_w")), intish(row.get("canvas_h"))),
                    visible_bbox=(
                        intish(row.get("visible_left")),
                        intish(row.get("visible_top")),
                        intish(row.get("visible_right_exclusive")),
                        intish(row.get("visible_bottom_exclusive")),
                    ),
                    paste_xy=(0, 0),
                    backup_path=None,
                    old_sha256=None,
                    new_sha256=None,
                    applied=False,
                    skipped=True,
                    skip_reason="excluded review/source/raw asset",
                )
                write_manifest_line(manifest_path, fix_action)
                continue

            backup_path = None
            new_hash = None

            if args.apply:
                backup_path = backup_file(src_path, root, backup_root)
                new_img.save(src_path)
                new_hash = sha256_file(src_path)
                stats["applied"] += 1
            else:
                stats["would_apply"] += 1

            fix_action = FixAction(
                path=rel_path,
                action=action_name,
                reason=reason,
                old_size=old_size,
                new_size=new_size,
                visible_bbox=bbox,
                paste_xy=paste_xy,
                backup_path=str(backup_path) if backup_path else None,
                old_sha256=old_hash,
                new_sha256=new_hash,
                applied=args.apply,
                skipped=False,
                skip_reason="",
            )
            write_manifest_line(manifest_path, fix_action)

            verb = "APPLIED" if args.apply else "WOULD APPLY"
            print(f"{verb}: {rel_path}")
            print(
                f"  {action_name}: {old_size[0]}x{old_size[1]} -> {new_size[0]}x{new_size[1]}"
            )
            print(f"  bbox={bbox}, paste_xy={paste_xy}, reason={reason}")

        except Exception as exc:
            stats["errors"] += 1
            print(f"ERROR: {rel_path}: {exc}", file=sys.stderr)

            fix_action = FixAction(
                path=rel_path,
                action="error",
                reason=str(exc),
                old_size=(intish(row.get("canvas_w")), intish(row.get("canvas_h"))),
                new_size=(0, 0),
                visible_bbox=None,
                paste_xy=(0, 0),
                backup_path=None,
                old_sha256=None,
                new_sha256=None,
                applied=False,
                skipped=True,
                skip_reason=str(exc),
            )
            write_manifest_line(manifest_path, fix_action)

    print()
    print("Done.")
    print(json.dumps(stats, indent=2))
    print()
    print(f"Manifest written to: {manifest_path}")

    if not args.apply:
        print()
        print("Dry run only. Re-run with --apply to modify files.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
