class_name MeridianCivicWallRuntimeCatalog
extends RefCounted

const CELL_SIZE := 32
const LOGICAL_GRID := Vector2i(14, 14)
const RUNTIME_GRID := Vector2i(16, 16)
const INVALID := Vector2i(-1, -1)

const ENTRIES := {
	"wall_00_00": {
	"coord": Vector2i(0, 0),
	"name": "masonry_cap_straight_a",
	"family": "wall_cap",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_01_00": {
	"coord": Vector2i(1, 0),
	"name": "masonry_cap_straight_b",
	"family": "wall_cap",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_02_00": {
	"coord": Vector2i(2, 0),
	"name": "masonry_cap_corner_a",
	"family": "wall_cap",
	"geometry": "corner",
	"condition": "intact",
	"auto": true,
	"ports": ["E", "S"],
	"topology": "corner_es",
	"scope": "topology_then_family_variant"
},
	"wall_03_00": {
	"coord": Vector2i(3, 0),
	"name": "masonry_cap_corner_b",
	"family": "wall_cap",
	"geometry": "corner",
	"condition": "intact",
	"auto": true,
	"ports": ["E", "S"],
	"topology": "corner_es",
	"scope": "topology_then_family_variant"
},
	"wall_04_00": {
	"coord": Vector2i(4, 0),
	"name": "masonry_cap_corner_c",
	"family": "wall_cap",
	"geometry": "corner",
	"condition": "intact",
	"auto": true,
	"ports": ["E", "S"],
	"topology": "corner_es",
	"scope": "topology_then_family_variant"
},
	"wall_05_00": {
	"coord": Vector2i(5, 0),
	"name": "masonry_cap_corner_d",
	"family": "wall_cap",
	"geometry": "corner",
	"condition": "intact",
	"auto": true,
	"ports": ["E", "S"],
	"topology": "corner_es_damaged",
	"scope": "topology_then_family_variant"
},
	"wall_06_00": {
	"coord": Vector2i(6, 0),
	"name": "masonry_cap_junction_a",
	"family": "wall_cap",
	"geometry": "junction",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E", "S"],
	"topology": "tee_wes",
	"scope": "topology_then_family_variant"
},
	"wall_07_00": {
	"coord": Vector2i(7, 0),
	"name": "masonry_cap_rounded_corner",
	"family": "wall_cap",
	"geometry": "rounded_corner",
	"condition": "intact",
	"auto": true,
	"ports": ["N", "E"],
	"topology": "corner_ne_rounded",
	"scope": "topology_then_family_variant"
},
	"wall_08_00": {
	"coord": Vector2i(8, 0),
	"name": "masonry_cap_junction_b",
	"family": "wall_cap",
	"geometry": "junction",
	"condition": "intact",
	"auto": true,
	"ports": ["N", "E", "S", "W"],
	"topology": "cross_nesw",
	"scope": "topology_then_family_variant"
},
	"wall_09_00": {
	"coord": Vector2i(9, 0),
	"name": "masonry_cap_junction_c",
	"family": "wall_cap",
	"geometry": "junction",
	"condition": "intact",
	"auto": true,
	"ports": ["N", "E", "S", "W"],
	"topology": "cross_nesw",
	"scope": "topology_then_family_variant"
},
	"wall_10_00": {
	"coord": Vector2i(10, 0),
	"name": "masonry_cap_junction_d",
	"family": "wall_cap",
	"geometry": "junction",
	"condition": "intact",
	"auto": true,
	"ports": ["N", "E", "S", "W"],
	"topology": "cross_nesw",
	"scope": "topology_then_family_variant"
},
	"wall_11_00": {
	"coord": Vector2i(11, 0),
	"name": "masonry_pier_isolated",
	"family": "wall_pier",
	"geometry": "isolated_pier",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_12_00": {
	"coord": Vector2i(12, 0),
	"name": "masonry_cap_straight_short_a",
	"family": "wall_cap",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_13_00": {
	"coord": Vector2i(13, 0),
	"name": "masonry_cap_straight_short_b",
	"family": "wall_cap",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_00_01": {
	"coord": Vector2i(0, 1),
	"name": "civic_arch_opening_large_a",
	"family": "civic_opening",
	"geometry": "arch_opening",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_01_01": {
	"coord": Vector2i(1, 1),
	"name": "civic_rect_opening_wide",
	"family": "civic_opening",
	"geometry": "rect_opening",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_02_01": {
	"coord": Vector2i(2, 1),
	"name": "civic_arch_opening_small",
	"family": "civic_opening",
	"geometry": "arch_opening",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_03_01": {
	"coord": Vector2i(3, 1),
	"name": "civic_recessed_window",
	"family": "civic_opening",
	"geometry": "window",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_04_01": {
	"coord": Vector2i(4, 1),
	"name": "civic_arch_opening_large_b",
	"family": "civic_opening",
	"geometry": "arch_opening",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_05_01": {
	"coord": Vector2i(5, 1),
	"name": "civic_arch_opening_medium",
	"family": "civic_opening",
	"geometry": "arch_opening",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_06_01": {
	"coord": Vector2i(6, 1),
	"name": "civic_triple_niche",
	"family": "civic_opening",
	"geometry": "niche",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_07_01": {
	"coord": Vector2i(7, 1),
	"name": "civic_barred_gate_wide",
	"family": "civic_opening",
	"geometry": "barred_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_08_01": {
	"coord": Vector2i(8, 1),
	"name": "civic_vertical_niche",
	"family": "civic_opening",
	"geometry": "niche",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_09_01": {
	"coord": Vector2i(9, 1),
	"name": "civic_barred_gate_narrow_a",
	"family": "civic_opening",
	"geometry": "barred_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_10_01": {
	"coord": Vector2i(10, 1),
	"name": "civic_barred_gate_narrow_b",
	"family": "civic_opening",
	"geometry": "barred_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_11_01": {
	"coord": Vector2i(11, 1),
	"name": "civic_tall_arched_gate",
	"family": "civic_opening",
	"geometry": "arched_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_12_01": {
	"coord": Vector2i(12, 1),
	"name": "civic_arched_door_amber_header",
	"family": "civic_opening",
	"geometry": "arched_door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_13_01": {
	"coord": Vector2i(13, 1),
	"name": "civic_triple_window_bay",
	"family": "civic_opening",
	"geometry": "window_bay",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_00_02": {
	"coord": Vector2i(0, 2),
	"name": "utility_railing_machine_a",
	"family": "utility_parapet",
	"geometry": "railing_machine",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_01_02": {
	"coord": Vector2i(1, 2),
	"name": "utility_railing_pier_a",
	"family": "utility_parapet",
	"geometry": "railing_pier",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_02_02": {
	"coord": Vector2i(2, 2),
	"name": "utility_railing_narrow",
	"family": "utility_parapet",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_03_02": {
	"coord": Vector2i(3, 2),
	"name": "utility_railing_pier_b",
	"family": "utility_parapet",
	"geometry": "railing_pier",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_04_02": {
	"coord": Vector2i(4, 2),
	"name": "utility_railing_machine_b",
	"family": "utility_parapet",
	"geometry": "railing_machine",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_05_02": {
	"coord": Vector2i(5, 2),
	"name": "utility_parapet_damaged",
	"family": "utility_parapet",
	"geometry": "damaged_transition",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_damage",
	"scope": "explicit_authored_only"
},
	"wall_06_02": {
	"coord": Vector2i(6, 2),
	"name": "utility_rounded_corner",
	"family": "utility_parapet",
	"geometry": "rounded_corner",
	"condition": "intact",
	"auto": true,
	"ports": ["E", "S"],
	"topology": "corner_es_rounded",
	"scope": "topology_then_family_variant"
},
	"wall_07_02": {
	"coord": Vector2i(7, 2),
	"name": "low_retaining_plain_a",
	"family": "retaining_wall",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_08_02": {
	"coord": Vector2i(8, 2),
	"name": "low_retaining_damaged_a",
	"family": "retaining_wall",
	"geometry": "straight",
	"condition": "worn",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_09_02": {
	"coord": Vector2i(9, 2),
	"name": "low_rail_plain_a",
	"family": "utility_parapet",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_10_02": {
	"coord": Vector2i(10, 2),
	"name": "low_rail_plain_b",
	"family": "utility_parapet",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_11_02": {
	"coord": Vector2i(11, 2),
	"name": "low_rail_amber_post",
	"family": "utility_parapet",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_12_02": {
	"coord": Vector2i(12, 2),
	"name": "service_panel_retaining",
	"family": "retaining_wall",
	"geometry": "service_panel",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_13_02": {
	"coord": Vector2i(13, 2),
	"name": "service_coil_retaining",
	"family": "retaining_wall",
	"geometry": "service_panel",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_00_03": {
	"coord": Vector2i(0, 3),
	"name": "rounded_retaining_corner_large",
	"family": "retaining_wall",
	"geometry": "rounded_corner",
	"condition": "intact",
	"auto": true,
	"ports": ["E", "S"],
	"topology": "corner_es_rounded",
	"scope": "topology_then_family_variant"
},
	"wall_01_03": {
	"coord": Vector2i(1, 3),
	"name": "pipe_retaining_straight_a",
	"family": "pipe_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_02_03": {
	"coord": Vector2i(2, 3),
	"name": "pipe_retaining_straight_b",
	"family": "pipe_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_03_03": {
	"coord": Vector2i(3, 3),
	"name": "pipe_retaining_straight_c",
	"family": "pipe_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_04_03": {
	"coord": Vector2i(4, 3),
	"name": "pipe_retaining_straight_d",
	"family": "pipe_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_05_03": {
	"coord": Vector2i(5, 3),
	"name": "pipe_retaining_corner",
	"family": "pipe_retaining",
	"geometry": "rounded_corner",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "S"],
	"topology": "corner_ws_rounded",
	"scope": "topology_then_family_variant"
},
	"wall_06_03": {
	"coord": Vector2i(6, 3),
	"name": "pipe_retaining_corner_small",
	"family": "pipe_retaining",
	"geometry": "rounded_corner",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "S"],
	"topology": "corner_ws_rounded",
	"scope": "topology_then_family_variant"
},
	"wall_07_03": {
	"coord": Vector2i(7, 3),
	"name": "low_pipe_wall",
	"family": "pipe_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_08_03": {
	"coord": Vector2i(8, 3),
	"name": "railing_plain_a",
	"family": "civic_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_09_03": {
	"coord": Vector2i(9, 3),
	"name": "railing_plain_b",
	"family": "civic_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_10_03": {
	"coord": Vector2i(10, 3),
	"name": "railing_plain_c",
	"family": "civic_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_11_03": {
	"coord": Vector2i(11, 3),
	"name": "amber_service_gate_a",
	"family": "service_gate_edge",
	"geometry": "gate_edge",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_12_03": {
	"coord": Vector2i(12, 3),
	"name": "amber_service_gate_b",
	"family": "service_gate_edge",
	"geometry": "gate_edge",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_13_03": {
	"coord": Vector2i(13, 3),
	"name": "railing_dense",
	"family": "civic_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_00_04": {
	"coord": Vector2i(0, 4),
	"name": "broken_masonry_corner",
	"family": "retaining_wall",
	"geometry": "broken_corner",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_damage",
	"scope": "explicit_authored_only"
},
	"wall_01_04": {
	"coord": Vector2i(1, 4),
	"name": "plain_masonry_wall_a",
	"family": "retaining_wall",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_02_04": {
	"coord": Vector2i(2, 4),
	"name": "plain_masonry_wall_damaged",
	"family": "retaining_wall",
	"geometry": "straight",
	"condition": "worn",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_03_04": {
	"coord": Vector2i(3, 4),
	"name": "pipe_corner_a",
	"family": "pipe_retaining",
	"geometry": "corner",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "manual_composite_corner",
	"scope": "explicit_authored_only"
},
	"wall_04_04": {
	"coord": Vector2i(4, 4),
	"name": "pipe_corner_b",
	"family": "pipe_retaining",
	"geometry": "corner",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "manual_composite_corner",
	"scope": "explicit_authored_only"
},
	"wall_05_04": {
	"coord": Vector2i(5, 4),
	"name": "pipe_retaining_straight_e",
	"family": "pipe_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_06_04": {
	"coord": Vector2i(6, 4),
	"name": "grille_retaining_straight_a",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_07_04": {
	"coord": Vector2i(7, 4),
	"name": "grille_retaining_terminal",
	"family": "grille_retaining",
	"geometry": "terminal",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_08_04": {
	"coord": Vector2i(8, 4),
	"name": "grille_retaining_straight_b",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_09_04": {
	"coord": Vector2i(9, 4),
	"name": "grille_retaining_straight_c",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_10_04": {
	"coord": Vector2i(10, 4),
	"name": "grille_retaining_straight_d",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_11_04": {
	"coord": Vector2i(11, 4),
	"name": "grille_retaining_straight_e",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_12_04": {
	"coord": Vector2i(12, 4),
	"name": "grille_retaining_broken",
	"family": "grille_retaining",
	"geometry": "broken",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_damage",
	"scope": "explicit_authored_only"
},
	"wall_13_04": {
	"coord": Vector2i(13, 4),
	"name": "grille_retaining_post",
	"family": "grille_retaining",
	"geometry": "post",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_00_05": {
	"coord": Vector2i(0, 5),
	"name": "grille_retaining_terminal_right",
	"family": "grille_retaining",
	"geometry": "terminal",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_01_05": {
	"coord": Vector2i(1, 5),
	"name": "sloped_retaining_ramp",
	"family": "retaining_transition",
	"geometry": "slope",
	"condition": "intact",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "slope_rise_east",
	"scope": "explicit_authored_only"
},
	"wall_02_05": {
	"coord": Vector2i(2, 5),
	"name": "grille_wall_a",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_03_05": {
	"coord": Vector2i(3, 5),
	"name": "grille_wall_b",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_04_05": {
	"coord": Vector2i(4, 5),
	"name": "grille_wall_c",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_05_05": {
	"coord": Vector2i(5, 5),
	"name": "grille_wall_d",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_06_05": {
	"coord": Vector2i(6, 5),
	"name": "grille_wall_post",
	"family": "grille_retaining",
	"geometry": "post",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_07_05": {
	"coord": Vector2i(7, 5),
	"name": "damaged_grille_wall",
	"family": "grille_retaining",
	"geometry": "broken",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_damage",
	"scope": "explicit_authored_only"
},
	"wall_08_05": {
	"coord": Vector2i(8, 5),
	"name": "heavy_grille_wall",
	"family": "grille_retaining",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_09_05": {
	"coord": Vector2i(9, 5),
	"name": "ornamental_rail_a",
	"family": "ornamental_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_10_05": {
	"coord": Vector2i(10, 5),
	"name": "ornamental_rail_b",
	"family": "ornamental_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_11_05": {
	"coord": Vector2i(11, 5),
	"name": "ornamental_rail_c",
	"family": "ornamental_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_12_05": {
	"coord": Vector2i(12, 5),
	"name": "ornamental_rail_teal_a",
	"family": "ornamental_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_13_05": {
	"coord": Vector2i(13, 5),
	"name": "ornamental_rail_teal_b",
	"family": "ornamental_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_00_06": {
	"coord": Vector2i(0, 6),
	"name": "ornamental_railing_intact",
	"family": "ornamental_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_01_06": {
	"coord": Vector2i(1, 6),
	"name": "damaged_railing_slope_a",
	"family": "retaining_transition",
	"geometry": "damaged_slope",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "slope_fall_east",
	"scope": "explicit_authored_only"
},
	"wall_02_06": {
	"coord": Vector2i(2, 6),
	"name": "damaged_railing_slope_b",
	"family": "retaining_transition",
	"geometry": "damaged_slope",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "slope_rise_east",
	"scope": "explicit_authored_only"
},
	"wall_03_06": {
	"coord": Vector2i(3, 6),
	"name": "ornamental_railing_post",
	"family": "ornamental_railing",
	"geometry": "railing_post",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_04_06": {
	"coord": Vector2i(4, 6),
	"name": "plain_wall_terminal",
	"family": "retaining_wall",
	"geometry": "terminal",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_05_06": {
	"coord": Vector2i(5, 6),
	"name": "industrial_panel_wall",
	"family": "industrial_facade",
	"geometry": "panel_wall",
	"condition": "worn",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_06_06": {
	"coord": Vector2i(6, 6),
	"name": "rubble_slope_a",
	"family": "rubble_transition",
	"geometry": "rubble_slope",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "rubble_slope_rise_east",
	"scope": "explicit_authored_only"
},
	"wall_07_06": {
	"coord": Vector2i(7, 6),
	"name": "rubble_slope_b",
	"family": "rubble_transition",
	"geometry": "rubble_slope",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "rubble_slope_rise_east",
	"scope": "explicit_authored_only"
},
	"wall_08_06": {
	"coord": Vector2i(8, 6),
	"name": "rubble_slope_c",
	"family": "rubble_transition",
	"geometry": "rubble_slope",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "rubble_slope_rise_east",
	"scope": "explicit_authored_only"
},
	"wall_09_06": {
	"coord": Vector2i(9, 6),
	"name": "rubble_slope_d",
	"family": "rubble_transition",
	"geometry": "rubble_slope",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "rubble_slope_rise_east",
	"scope": "explicit_authored_only"
},
	"wall_10_06": {
	"coord": Vector2i(10, 6),
	"name": "heavy_industrial_facade_a",
	"family": "industrial_facade",
	"geometry": "heavy_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_11_06": {
	"coord": Vector2i(11, 6),
	"name": "heavy_industrial_facade_b",
	"family": "industrial_facade",
	"geometry": "heavy_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_12_06": {
	"coord": Vector2i(12, 6),
	"name": "heavy_industrial_facade_c",
	"family": "industrial_facade",
	"geometry": "heavy_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_13_06": {
	"coord": Vector2i(13, 6),
	"name": "heavy_industrial_facade_d",
	"family": "industrial_facade",
	"geometry": "heavy_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_00_07": {
	"coord": Vector2i(0, 7),
	"name": "heavy_industrial_facade_e",
	"family": "industrial_facade",
	"geometry": "heavy_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_01_07": {
	"coord": Vector2i(1, 7),
	"name": "heavy_industrial_facade_f",
	"family": "industrial_facade",
	"geometry": "heavy_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_02_07": {
	"coord": Vector2i(2, 7),
	"name": "heavy_industrial_facade_g",
	"family": "industrial_facade",
	"geometry": "heavy_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_03_07": {
	"coord": Vector2i(3, 7),
	"name": "service_facade_small",
	"family": "service_facade",
	"geometry": "panel_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_04_07": {
	"coord": Vector2i(4, 7),
	"name": "civic_gate_rect_open",
	"family": "service_facade",
	"geometry": "rect_opening",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_05_07": {
	"coord": Vector2i(5, 7),
	"name": "service_facade_panel",
	"family": "service_facade",
	"geometry": "panel_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_06_07": {
	"coord": Vector2i(6, 7),
	"name": "service_facade_window",
	"family": "service_facade",
	"geometry": "window",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_07_07": {
	"coord": Vector2i(7, 7),
	"name": "service_facade_door",
	"family": "service_facade",
	"geometry": "door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_08_07": {
	"coord": Vector2i(8, 7),
	"name": "ornate_gate_dark_a",
	"family": "ornate_facade",
	"geometry": "gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_09_07": {
	"coord": Vector2i(9, 7),
	"name": "ornate_gate_dark_b",
	"family": "ornate_facade",
	"geometry": "gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_10_07": {
	"coord": Vector2i(10, 7),
	"name": "ornate_machine_facade",
	"family": "ornate_facade",
	"geometry": "machine_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_11_07": {
	"coord": Vector2i(11, 7),
	"name": "arched_door_civic_a",
	"family": "ornate_facade",
	"geometry": "arched_door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_12_07": {
	"coord": Vector2i(12, 7),
	"name": "arched_door_civic_b",
	"family": "ornate_facade",
	"geometry": "arched_door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_13_07": {
	"coord": Vector2i(13, 7),
	"name": "arched_door_civic_c",
	"family": "ornate_facade",
	"geometry": "arched_door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_00_08": {
	"coord": Vector2i(0, 8),
	"name": "ornate_arch_gate_a",
	"family": "ornate_facade",
	"geometry": "arched_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_01_08": {
	"coord": Vector2i(1, 8),
	"name": "ornate_arch_gate_b",
	"family": "ornate_facade",
	"geometry": "arched_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_02_08": {
	"coord": Vector2i(2, 8),
	"name": "ornate_arch_gate_c",
	"family": "ornate_facade",
	"geometry": "arched_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_03_08": {
	"coord": Vector2i(3, 8),
	"name": "ornate_arch_gate_d",
	"family": "ornate_facade",
	"geometry": "arched_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_04_08": {
	"coord": Vector2i(4, 8),
	"name": "ornate_arch_gate_e",
	"family": "ornate_facade",
	"geometry": "arched_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_05_08": {
	"coord": Vector2i(5, 8),
	"name": "ornate_arch_gate_f",
	"family": "ornate_facade",
	"geometry": "arched_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_06_08": {
	"coord": Vector2i(6, 8),
	"name": "ornate_small_door",
	"family": "ornate_facade",
	"geometry": "door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_07_08": {
	"coord": Vector2i(7, 8),
	"name": "ornate_facade_plain",
	"family": "ornate_facade",
	"geometry": "plain_facade",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_08_08": {
	"coord": Vector2i(8, 8),
	"name": "teal_double_door_a",
	"family": "station_facade",
	"geometry": "double_door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_09_08": {
	"coord": Vector2i(9, 8),
	"name": "teal_double_door_b",
	"family": "station_facade",
	"geometry": "double_door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_10_08": {
	"coord": Vector2i(10, 8),
	"name": "dark_double_door",
	"family": "station_facade",
	"geometry": "double_door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_11_08": {
	"coord": Vector2i(11, 8),
	"name": "teal_double_door_c",
	"family": "station_facade",
	"geometry": "double_door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_12_08": {
	"coord": Vector2i(12, 8),
	"name": "teal_double_door_d",
	"family": "station_facade",
	"geometry": "double_door",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_13_08": {
	"coord": Vector2i(13, 8),
	"name": "vertical_service_gate",
	"family": "station_facade",
	"geometry": "vertical_gate",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_00_09": {
	"coord": Vector2i(0, 9),
	"name": "sealed_hazard_door",
	"family": "damaged_facade",
	"geometry": "sealed_door",
	"condition": "worn",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_01_09": {
	"coord": Vector2i(1, 9),
	"name": "ornate_gate_damaged_top",
	"family": "damaged_facade",
	"geometry": "gate",
	"condition": "worn",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_02_09": {
	"coord": Vector2i(2, 9),
	"name": "rubble_breach_left",
	"family": "rubble_transition",
	"geometry": "breach",
	"condition": "damaged",
	"auto": false,
	"ports": ["E"],
	"topology": "breach_left_terminal",
	"scope": "explicit_authored_only"
},
	"wall_03_09": {
	"coord": Vector2i(3, 9),
	"name": "door_rubble_left",
	"family": "damaged_facade",
	"geometry": "door_breach",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_04_09": {
	"coord": Vector2i(4, 9),
	"name": "rubble_breach_center_a",
	"family": "rubble_transition",
	"geometry": "breach",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "breach_center",
	"scope": "explicit_authored_only"
},
	"wall_05_09": {
	"coord": Vector2i(5, 9),
	"name": "rubble_breach_right_a",
	"family": "rubble_transition",
	"geometry": "breach",
	"condition": "damaged",
	"auto": false,
	"ports": ["W"],
	"topology": "breach_right_terminal",
	"scope": "explicit_authored_only"
},
	"wall_06_09": {
	"coord": Vector2i(6, 9),
	"name": "rubble_breach_center_b",
	"family": "rubble_transition",
	"geometry": "breach",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "breach_center",
	"scope": "explicit_authored_only"
},
	"wall_07_09": {
	"coord": Vector2i(7, 9),
	"name": "rubble_pile_open",
	"family": "rubble_transition",
	"geometry": "rubble_open",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "rubble_open",
	"scope": "explicit_authored_only"
},
	"wall_08_09": {
	"coord": Vector2i(8, 9),
	"name": "collapsed_facade_window",
	"family": "damaged_facade",
	"geometry": "collapsed_window",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_09_09": {
	"coord": Vector2i(9, 9),
	"name": "intact_window_facade_a",
	"family": "damaged_facade",
	"geometry": "window",
	"condition": "worn",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_10_09": {
	"coord": Vector2i(10, 9),
	"name": "broken_facade_large_hole",
	"family": "damaged_facade",
	"geometry": "breach",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_11_09": {
	"coord": Vector2i(11, 9),
	"name": "destroyed_facade_void",
	"family": "damaged_facade",
	"geometry": "breach",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_12_09": {
	"coord": Vector2i(12, 9),
	"name": "intact_window_facade_b",
	"family": "damaged_facade",
	"geometry": "window",
	"condition": "worn",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_13_09": {
	"coord": Vector2i(13, 9),
	"name": "circular_sealed_wall",
	"family": "damaged_facade",
	"geometry": "sealed_wall",
	"condition": "worn",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_00_10": {
	"coord": Vector2i(0, 10),
	"name": "rubble_breach_wall",
	"family": "rubble_transition",
	"geometry": "breach",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "breach_center",
	"scope": "explicit_authored_only"
},
	"wall_01_10": {
	"coord": Vector2i(1, 10),
	"name": "narrow_gate_facade",
	"family": "industrial_facade",
	"geometry": "gate",
	"condition": "worn",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_02_10": {
	"coord": Vector2i(2, 10),
	"name": "rubble_pile_large",
	"family": "rubble_transition",
	"geometry": "rubble_open",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "rubble_open",
	"scope": "explicit_authored_only"
},
	"wall_03_10": {
	"coord": Vector2i(3, 10),
	"name": "rubble_pile_long",
	"family": "rubble_transition",
	"geometry": "rubble_open",
	"condition": "damaged",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "rubble_span",
	"scope": "explicit_authored_only"
},
	"wall_04_10": {
	"coord": Vector2i(4, 10),
	"name": "damaged_service_facade",
	"family": "damaged_facade",
	"geometry": "service_facade",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_05_10": {
	"coord": Vector2i(5, 10),
	"name": "broken_railing_facade",
	"family": "damaged_facade",
	"geometry": "railing_facade",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_06_10": {
	"coord": Vector2i(6, 10),
	"name": "hazard_wall_damaged",
	"family": "hazard_facade",
	"geometry": "wall",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_damage",
	"scope": "explicit_authored_only"
},
	"wall_07_10": {
	"coord": Vector2i(7, 10),
	"name": "service_wall_broken_terminal",
	"family": "hazard_facade",
	"geometry": "terminal",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_damage",
	"scope": "explicit_authored_only"
},
	"wall_08_10": {
	"coord": Vector2i(8, 10),
	"name": "hazard_gate_side_a",
	"family": "hazard_facade",
	"geometry": "gate_side",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_09_10": {
	"coord": Vector2i(9, 10),
	"name": "hazard_gate_side_b",
	"family": "hazard_facade",
	"geometry": "gate_side",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_10_10": {
	"coord": Vector2i(10, 10),
	"name": "hazard_retaining_straight_a",
	"family": "hazard_facade",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_11_10": {
	"coord": Vector2i(11, 10),
	"name": "hazard_retaining_straight_b",
	"family": "hazard_facade",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_12_10": {
	"coord": Vector2i(12, 10),
	"name": "service_panel_hazard",
	"family": "hazard_facade",
	"geometry": "service_panel",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_13_10": {
	"coord": Vector2i(13, 10),
	"name": "hazard_retaining_straight_c",
	"family": "hazard_facade",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_00_11": {
	"coord": Vector2i(0, 11),
	"name": "hazard_railing_wall",
	"family": "hazard_facade",
	"geometry": "railing_wall",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_01_11": {
	"coord": Vector2i(1, 11),
	"name": "hazard_retaining_wall",
	"family": "hazard_facade",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_02_11": {
	"coord": Vector2i(2, 11),
	"name": "rubble_cluster_low",
	"family": "rubble_transition",
	"geometry": "rubble_open",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "rubble_open",
	"scope": "explicit_authored_only"
},
	"wall_03_11": {
	"coord": Vector2i(3, 11),
	"name": "hazard_gate_panel",
	"family": "hazard_facade",
	"geometry": "gate_panel",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_04_11": {
	"coord": Vector2i(4, 11),
	"name": "service_gate_panel",
	"family": "hazard_facade",
	"geometry": "service_panel",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_05_11": {
	"coord": Vector2i(5, 11),
	"name": "hazard_retaining_plain",
	"family": "hazard_facade",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_06_11": {
	"coord": Vector2i(6, 11),
	"name": "hazard_plate_wall",
	"family": "hazard_facade",
	"geometry": "plate_wall",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_punctuation",
	"scope": "explicit_authored_only"
},
	"wall_07_11": {
	"coord": Vector2i(7, 11),
	"name": "hazard_slope_transition",
	"family": "hazard_transition",
	"geometry": "slope",
	"condition": "intact",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "hazard_slope_fall_east",
	"scope": "explicit_authored_only"
},
	"wall_08_11": {
	"coord": Vector2i(8, 11),
	"name": "hazard_inner_corner_a",
	"family": "hazard_transition",
	"geometry": "angled_corner",
	"condition": "intact",
	"auto": true,
	"ports": ["E", "S"],
	"topology": "corner_es_diagonal",
	"scope": "topology_then_family_variant"
},
	"wall_09_11": {
	"coord": Vector2i(9, 11),
	"name": "canal_edge_straight_a",
	"family": "canal_edge",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_10_11": {
	"coord": Vector2i(10, 11),
	"name": "canal_edge_straight_b",
	"family": "canal_edge",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_11_11": {
	"coord": Vector2i(11, 11),
	"name": "canal_corner_a",
	"family": "canal_edge",
	"geometry": "angled_corner",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "S"],
	"topology": "canal_corner_ws",
	"scope": "topology_then_family_variant"
},
	"wall_12_11": {
	"coord": Vector2i(12, 11),
	"name": "canal_corner_b",
	"family": "canal_edge",
	"geometry": "angled_corner",
	"condition": "intact",
	"auto": true,
	"ports": ["E", "S"],
	"topology": "canal_corner_es",
	"scope": "topology_then_family_variant"
},
	"wall_13_11": {
	"coord": Vector2i(13, 11),
	"name": "canal_edge_straight_c",
	"family": "canal_edge",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_00_12": {
	"coord": Vector2i(0, 12),
	"name": "chain_railing_a",
	"family": "ornamental_railing",
	"geometry": "chain_railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_01_12": {
	"coord": Vector2i(1, 12),
	"name": "chain_railing_b",
	"family": "ornamental_railing",
	"geometry": "chain_railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_02_12": {
	"coord": Vector2i(2, 12),
	"name": "chain_railing_c",
	"family": "ornamental_railing",
	"geometry": "chain_railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_03_12": {
	"coord": Vector2i(3, 12),
	"name": "chain_railing_d",
	"family": "ornamental_railing",
	"geometry": "chain_railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_04_12": {
	"coord": Vector2i(4, 12),
	"name": "broken_chain_railing",
	"family": "ornamental_railing",
	"geometry": "broken_railing",
	"condition": "damaged",
	"auto": false,
	"ports": [],
	"topology": "authored_damage",
	"scope": "explicit_authored_only"
},
	"wall_05_12": {
	"coord": Vector2i(5, 12),
	"name": "stair_railing_transition",
	"family": "retaining_transition",
	"geometry": "stair_transition",
	"condition": "intact",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "stair_transition",
	"scope": "explicit_authored_only"
},
	"wall_06_12": {
	"coord": Vector2i(6, 12),
	"name": "hazard_stair_slope",
	"family": "hazard_transition",
	"geometry": "stair_slope",
	"condition": "intact",
	"auto": false,
	"ports": ["W", "E"],
	"topology": "hazard_stair_rise_east",
	"scope": "explicit_authored_only"
},
	"wall_07_12": {
	"coord": Vector2i(7, 12),
	"name": "hazard_wall_straight",
	"family": "hazard_facade",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_08_12": {
	"coord": Vector2i(8, 12),
	"name": "hazard_corner_diagonal",
	"family": "hazard_transition",
	"geometry": "angled_corner",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "manual_diagonal_corner",
	"scope": "explicit_authored_only"
},
	"wall_09_12": {
	"coord": Vector2i(9, 12),
	"name": "canal_wall_straight_a",
	"family": "canal_edge",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_10_12": {
	"coord": Vector2i(10, 12),
	"name": "canal_wall_straight_b",
	"family": "canal_edge",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_11_12": {
	"coord": Vector2i(11, 12),
	"name": "canal_corner_diagonal",
	"family": "canal_edge",
	"geometry": "angled_corner",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "manual_canal_diagonal_corner",
	"scope": "explicit_authored_only"
},
	"wall_12_12": {
	"coord": Vector2i(12, 12),
	"name": "canal_wall_straight_c",
	"family": "canal_edge",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_13_12": {
	"coord": Vector2i(13, 12),
	"name": "canal_pool_vertical_end",
	"family": "canal_edge",
	"geometry": "endcap",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "isolated_pool_end",
	"scope": "explicit_authored_only"
},
	"wall_00_13": {
	"coord": Vector2i(0, 13),
	"name": "service_railing_a",
	"family": "service_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_01_13": {
	"coord": Vector2i(1, 13),
	"name": "service_railing_b",
	"family": "service_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_02_13": {
	"coord": Vector2i(2, 13),
	"name": "hazard_service_railing",
	"family": "service_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_03_13": {
	"coord": Vector2i(3, 13),
	"name": "industrial_wall_panel",
	"family": "industrial_facade",
	"geometry": "panel_wall",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_04_13": {
	"coord": Vector2i(4, 13),
	"name": "service_railing_c",
	"family": "service_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_05_13": {
	"coord": Vector2i(5, 13),
	"name": "hazard_service_wall",
	"family": "industrial_facade",
	"geometry": "hazard_wall",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "authored_special",
	"scope": "explicit_authored_only"
},
	"wall_06_13": {
	"coord": Vector2i(6, 13),
	"name": "pipe_service_railing",
	"family": "service_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_07_13": {
	"coord": Vector2i(7, 13),
	"name": "service_railing_d",
	"family": "service_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_08_13": {
	"coord": Vector2i(8, 13),
	"name": "service_railing_e",
	"family": "service_railing",
	"geometry": "railing",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_09_13": {
	"coord": Vector2i(9, 13),
	"name": "canal_pool_corner_left",
	"family": "canal_edge",
	"geometry": "corner",
	"condition": "intact",
	"auto": true,
	"ports": ["E", "S"],
	"topology": "canal_pool_corner_es",
	"scope": "topology_then_family_variant"
},
	"wall_10_13": {
	"coord": Vector2i(10, 13),
	"name": "canal_pool_straight_a",
	"family": "canal_edge",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_11_13": {
	"coord": Vector2i(11, 13),
	"name": "canal_pool_straight_b",
	"family": "canal_edge",
	"geometry": "straight",
	"condition": "intact",
	"auto": true,
	"ports": ["W", "E"],
	"topology": "straight_we",
	"scope": "topology_then_family_variant"
},
	"wall_12_13": {
	"coord": Vector2i(12, 13),
	"name": "canal_pool_frame_end",
	"family": "canal_edge",
	"geometry": "endcap",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "manual_pool_frame_end",
	"scope": "explicit_authored_only"
},
	"wall_13_13": {
	"coord": Vector2i(13, 13),
	"name": "canal_pool_curved_corner",
	"family": "canal_edge",
	"geometry": "rounded_corner",
	"condition": "intact",
	"auto": false,
	"ports": [],
	"topology": "manual_pool_curved_corner",
	"scope": "explicit_authored_only"
}
}

const AUTO_VARIANTS := {
	"straight_we|wall_cap": [Vector2i(0, 0), Vector2i(1, 0), Vector2i(12, 0), Vector2i(13, 0)],
	"corner_es|wall_cap": [Vector2i(2, 0), Vector2i(3, 0), Vector2i(4, 0)],
	"corner_es_damaged|wall_cap": [Vector2i(5, 0)],
	"tee_wes|wall_cap": [Vector2i(6, 0)],
	"corner_ne_rounded|wall_cap": [Vector2i(7, 0)],
	"cross_nesw|wall_cap": [Vector2i(8, 0), Vector2i(9, 0), Vector2i(10, 0)],
	"straight_we|utility_parapet": [Vector2i(2, 2), Vector2i(9, 2), Vector2i(10, 2), Vector2i(11, 2)],
	"corner_es_rounded|utility_parapet": [Vector2i(6, 2)],
	"straight_we|retaining_wall": [Vector2i(7, 2), Vector2i(8, 2), Vector2i(1, 4), Vector2i(2, 4)],
	"corner_es_rounded|retaining_wall": [Vector2i(0, 3)],
	"straight_we|pipe_retaining": [Vector2i(1, 3), Vector2i(2, 3), Vector2i(3, 3), Vector2i(4, 3), Vector2i(7, 3), Vector2i(5, 4)],
	"corner_ws_rounded|pipe_retaining": [Vector2i(5, 3), Vector2i(6, 3)],
	"straight_we|civic_railing": [Vector2i(8, 3), Vector2i(9, 3), Vector2i(10, 3), Vector2i(13, 3)],
	"straight_we|grille_retaining": [Vector2i(6, 4), Vector2i(8, 4), Vector2i(9, 4), Vector2i(10, 4), Vector2i(11, 4), Vector2i(2, 5), Vector2i(3, 5), Vector2i(4, 5), Vector2i(5, 5), Vector2i(8, 5)],
	"straight_we|ornamental_railing": [Vector2i(9, 5), Vector2i(10, 5), Vector2i(11, 5), Vector2i(12, 5), Vector2i(13, 5), Vector2i(0, 6), Vector2i(0, 12), Vector2i(1, 12), Vector2i(2, 12), Vector2i(3, 12)],
	"straight_we|hazard_facade": [Vector2i(10, 10), Vector2i(11, 10), Vector2i(13, 10), Vector2i(1, 11), Vector2i(5, 11), Vector2i(7, 12)],
	"corner_es_diagonal|hazard_transition": [Vector2i(8, 11)],
	"straight_we|canal_edge": [Vector2i(9, 11), Vector2i(10, 11), Vector2i(13, 11), Vector2i(9, 12), Vector2i(10, 12), Vector2i(12, 12), Vector2i(10, 13), Vector2i(11, 13)],
	"canal_corner_ws|canal_edge": [Vector2i(11, 11)],
	"canal_corner_es|canal_edge": [Vector2i(12, 11)],
	"straight_we|service_railing": [Vector2i(0, 13), Vector2i(1, 13), Vector2i(2, 13), Vector2i(4, 13), Vector2i(6, 13), Vector2i(7, 13), Vector2i(8, 13)],
	"canal_pool_corner_es|canal_edge": [Vector2i(9, 13)]
}

static func get_entry(id: StringName) -> Dictionary:
	return (ENTRIES.get(String(id), {}) as Dictionary).duplicate(true)

static func variants(topology: StringName, family: StringName) -> Array:
	var key := "%s|%s" % [String(topology), String(family)]
	return (AUTO_VARIANTS.get(key, []) as Array).duplicate()

static func is_valid_runtime_coord(coord: Vector2i) -> bool:
	return coord.x >= 0 and coord.y >= 0 and coord.x < 14 and coord.y < 14

static func source_region(coord: Vector2i) -> Rect2i:
	if not is_valid_runtime_coord(coord):
		return Rect2i()
	return Rect2i(coord * CELL_SIZE, Vector2i.ONE * CELL_SIZE)